### ISSUE TITLE
Press space to move the canvas.

### ISSUE THREAD

**Issue by sunnykgupta** [Ajeet1606/sketchify#1]
Most open canvas tools allow you to move around the canvas when holding down spacebar.
Opening this issue with an intention to contribute back via a PR to add that functionality.

**Comment by sunnykgupta** [comment]
Can you assign this to me?

**Comment by Ajeet1606** [comment]
Hey Sunny, sure thing, it's my honor to learn from your experiences, I've planned many more improvements (listed on Readme file) for myself as well, this is the very basic version I shared yesterday out of excitement. I'm open to your feedback on codebase, approach or in general.
Thanks for pointing out and coming up for the support, means a lot!

**Comment by Ajeet1606** [comment]
Hi Sunny, it's been a long time and we already have implemented proper scroll & zoom features so I believe we can close this issue now and before that would love to get your thoughts.
