### ISSUE TITLE
When zooming in, the cursor and the sketch are not aligning

### ISSUE THREAD

**Issue by starc007** [Ajeet1606/sketchify#8]
Working fine if you are not zooming in, whenever you zoom in the cursor and the sketch line is not aligning 

https://github.com/user-attachments/assets/eeb46e82-7957-4a5c-894e-6856a432eeea

**Comment by Ajeet1606** [comment]
Thanks for the contribution bro, looking forward to building together.
Assigning this to You!

**Comment by Ajeet1606** [comment]
Please fork the repo and make the changes in Dev branch or create a new one as per your convenience..
